import re
from enum import Enum


class Types(Enum):
    extensions = 1
    themes = 2


# 分类
# https://chrome.google.com/webstore/category/{Category}?gl=us&hl=en
class Category(Enum):
    accessibility = "ext/22-accessibility"
    blogging = "ext/10-blogging"
    web_development = "ext/11-web-development"
    fun = "ext/14-fun"
    news = "ext/6-news"
    photos = "ext/28-photos"
    productivity = "ext/7-productivity"
    search_tools = "ext/38-search-tools"
    shopping = "ext/12-shopping"
    communication = "ext/1-communication"
    sports = "ext/13-sports"


# 榜单
# https://chrome.google.com/webstore/category/collection/{Collection}?gl=us&hl=en
class Collection(Enum):
    top_accessibility = "3p_accessibility_extensions"
    top_blogging = "top_picks_blogging"
    top_web_development = "top_picks_web-development"
    top_fun = "top_picks_fun"
    top_news = "top_picks_news"
    top_photos = "top_picks_photos"
    top_productivity = "top_picks_productivity"
    top_search_tools = "top_picks_search-tools"
    top_shopping = "top_picks_shopping"
    top_communication = "top_picks_communication"
    top_sports = "top_picks_sports"


class Country(Enum):
    ar = "AR"
    ae = "AE"
    eg = "EG"
    ie = "IE"
    ee = "EE"
    at = "AT"
    au = "AU"
    pa = "PA"
    bg = "BG"
    be = "BE"
    pl = "PL"
    dk = "DK"
    de = "DE"
    ru = "RU"
    ec = "EC"
    fr = "FR"
    ph = "PH"
    fi = "FI"
    co = "CO"
    cu = "CU"
    nl = "NL"
    ca = "CA"
    cz = "CZ"
    lt = "LT"
    ro = "RO"
    my = "MY"
    us = "US"
    pe = "PE"
    ma = "MA"
    mx = "MX"
    za = "ZA"
    no = "NO"
    pt = "PT"
    jp = "JP"
    se = "SE"
    ch = "CH"
    sa = "SA"
    sk = "SK"
    tw = "TW"
    th = "TH"
    tr = "TR"
    ve = "VE"
    ua = "UA"
    es = "ES"
    gr = "GR"
    hk = "HK"
    sg = "SG"
    nz = "NZ"
    hu = "HU"
    il = "IL"
    it = "IT"
    IN = "IN"
    id = "ID"
    gb = "GB"
    vn = "VN"
    cl = "CL"
    cn = "CN"


class Language(Enum):
    ar = "ar"
    et = "et"
    bg = "bg"
    pl = "pl"
    fa = "fa"
    da = "da"
    de = "de"
    ru = "ru"
    fr = "fr"
    fil = "fil"
    fi = "fi"
    gu = "gu"
    ko = "ko"
    nl = "nl"
    ca = "ca"
    cs = "cs"
    hr = "hr"
    lv = "lv"
    lt = "lt"
    ro = "ro"
    mr = "mr"
    ml = "ml"
    ms = "ms"
    bn = "bn"
    no = "no"
    br = "pt_BR"
    pt = "pt_PT"
    jp = "ja"
    sv = "sv"
    sr = "sr"
    sk = "sk"
    sl = "sl"
    te = "te"
    ta = "ta"
    th = "th"
    tr = "tr"
    uk = "uk"
    es = "es"
    # es= "es_419"
    iw = "iw"
    el = "el"
    hu = "hu"
    it = "it"
    hi = "hi"
    IN = "in"
    en = "en"
    us = "en_US"
    gb = "en_GB"
    vi = "vi"
    tw = "zh_TW"
    cn = "zh_CN"
